# Generated by Django 3.0.8 on 2020-09-22 14:56

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_agemorbiditychart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellor',
            name='profile_pic',
            field=models.ImageField(upload_to=authentication.models.path_and_rename_counsellor),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='media/images/users/default_pic.png', null=True, upload_to=authentication.models.path_and_rename),
        ),
    ]
