# Generated by Django 3.1.1 on 2020-09-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200922_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateDisorderChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=4)),
            ],
        ),
    ]
