# Generated by Django 3.0.8 on 2020-09-15 12:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20200915_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='counsellors_consulted',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), default=list, size=3),
        ),
    ]
