# Generated by Django 3.1.1 on 2020-09-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_statedisorderchart_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statedisorderchart',
            name='state',
            field=models.CharField(max_length=16),
        ),
    ]
