# Generated by Django 3.0.8 on 2020-09-16 13:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20200915_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='counsellors_consulted',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
