# Generated by Django 3.1.1 on 2020-09-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20200929_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuicidalRiskChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=16)),
                ('percentage', models.FloatField()),
            ],
        ),
    ]
