# Generated by Django 3.0.8 on 2020-09-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20200916_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellor',
            name='profile_pic',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
