# Generated by Django 3.0.8 on 2020-09-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20200916_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellor',
            name='profile_pic',
            field=models.ImageField(upload_to='images/counsellors/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(upload_to='images/users/'),
        ),
    ]
