# Generated by Django 3.1.1 on 2020-09-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20200929_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumanResourcesChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=16)),
                ('psychiatrist', models.FloatField()),
                ('psychologist', models.FloatField()),
                ('social_workers', models.FloatField()),
            ],
        ),
    ]
