# Generated by Django 3.0.8 on 2020-09-16 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20200916_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='email',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.User'),
        ),
    ]
