# Generated by Django 3.0.7 on 2020-10-16 14:09

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_humanresourceschart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anonymous_User',
            fields=[
                ('id', models.IntegerField(default=-1, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ChatBots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('groupId', models.BigIntegerField()),
                ('clientGroupId', models.CharField(max_length=16)),
                ('message', models.CharField(max_length=512)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='answers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=64), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='counsellors_consulted',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='progress_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='questions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=64), null=True, size=None),
        ),
        migrations.CreateModel(
            name='Anonymous_Profile',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authentication.Anonymous_User')),
                ('progress_file', models.FileField(upload_to='')),
                ('counsellors_consulted', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=64), size=None)),
                ('questions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=64), size=None)),
                ('answers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=64), size=None)),
            ],
        ),
    ]
