# Generated by Django 3.0.8 on 2020-09-16 13:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20200916_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pic',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='images/articles'), size=None),
        ),
    ]
