# Generated by Django 3.1.2 on 2020-10-18 11:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_auto_20201018_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='progress_file',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='questions',
        ),
        migrations.AddField(
            model_name='chatbots',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='datetime',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, null=True, size=None),
        ),
        migrations.DeleteModel(
            name='Anonymous_Profile',
        ),
    ]
