# Generated by Django 3.0.8 on 2020-09-16 14:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_auto_20200916_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pic',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to=''), size=None),
        ),
    ]
