# Generated by Django 3.1.2 on 2020-10-18 12:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_auto_20201018_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
        migrations.CreateModel(
            name='MentalStates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=16)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2020, 10, 18, 12, 9, 18, 876662, tzinfo=utc))),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
        ),
    ]
