# Generated by Django 3.1.2 on 2020-10-18 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_auto_20201018_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anonymous_user',
            old_name='id',
            new_name='uid',
        ),
    ]
