# Generated by Django 3.0.8 on 2020-09-16 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_auto_20200916_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='desc',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='article',
            name='email',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.User'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pic',
            field=models.ImageField(blank=True, upload_to='images/articles'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
