# Generated by Django 3.1.2 on 2020-10-18 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_auto_20201018_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anonymous_user',
            old_name='uid',
            new_name='id',
        ),
    ]
