# Generated by Django 3.0.8 on 2020-09-16 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_auto_20200916_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='desc',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.User'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pic',
            field=models.ImageField(null=True, upload_to='images/articles'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
