# Generated by Django 3.1.2 on 2020-10-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_auto_20201018_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymous_user',
            name='username',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
