# Generated by Django 3.1.2 on 2020-10-19 17:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_auto_20201019_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbots',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
